実際に計算したanswerをもとにdbにデータを格納する（コード反映）
kanakof/personality_django pull request #13
Opened 2023-07-05 15:15 UTC by kanakof

こちらに、Issueにてアサインされたものを上げていきます

2023-07-05 15:21 UTC, kanakof commented
@DaisukeMiyazaki 
先日アサインして頂いたformからDB格納の部分、すごく時間かかりましたが、やっと完成しました…！
今回は、ファイルごとにpushしてプルリクを細かく切ることを意識しました…！
いつもありがとう！！

2023-07-10 00:29 UTC, DaisukeMiyazaki requested changes
@kanakof 全体的に方向性としては良いと思います！一部細かいところだけレビューしたので、こちら反映おねがいしますー

2023-07-10 00:29 UTC, DaisukeMiyazaki commented on app/questions/models.py
> +    body = models.CharField(max_length=100, null=True, blank=True)
@kanakof must: questionのbodyがないものって許可しなくても良いと思うので、そもそもmax_lengthのみで良いと思います！他の引数はいらないかと。

2023-07-10 00:29 UTC, DaisukeMiyazaki commented on app/questions/templates/questions/question_list.html
> +            <label><input type="radio" name="gender" value="3" id="gender-none">無回答</label>
@kanakof nit: 変数の命名規則には snake case, camel case、kebab case等あります。
https://designsupply-web.com/media/development/4052/

このプラクティスは実務でも基本1つのものに揃えるというのが作法です。backend側と揃えて snake caseにしておきましょう。gender_female .. ですね

2023-07-10 00:29 UTC, DaisukeMiyazaki commented on app/questions/views.py
> +
@kanakof 👍よく実装できました！
imo: questionの数が必ず18個あるとは限らないので、自分ならこう書きます

```
count = Question.objects.count()
for i in range(1, count + 1): # indexは1からとする
```

2023-07-10 00:29 UTC, DaisukeMiyazaki commented on app/questions/forms.py
must: 使わないコメントアウトされたコードはPRレビューの際には消してもらうようお願いします。

2023-07-10 00:29 UTC, DaisukeMiyazaki commented on app/questions/fixtures/questions.yaml
@kanakof nits:このままマージしても問題ないですが他ブランチと混ざっている、か意図的に入れているかな？

2023-07-10 00:35 UTC, DaisukeMiyazaki commented on app/questions/forms.py
ちなみに記録用であれば例えば以下のようなコメントも残すなら、正解です。実際実務でも乱用厳禁だけれどあります。
```
# UserFormのテンプレート
# 今後のmodelForm実装のときに参照するよう残す 
# https://github.com/kanakof/personality_django/pull/13
```

2023-07-10 07:34 UTC, kanakof commented on app/questions/models.py
> +    body = models.CharField(max_length=100, null=True, blank=True)
エラー対策で一応追加していたのですが、了解です！！
models.pyに反映しますね！

2023-07-10 07:54 UTC, kanakof commented on app/questions/templates/questions/question_list.html
> +            <label><input type="radio" name="gender" value="3" id="gender-none">無回答</label>
@DaisukeMiyazaki 
命名規則、とても参考になります！
わかりました！idやnameの部分はすべてsnake case に揃えますね！ありがとうございます！

2023-07-10 07:56 UTC, kanakof commented on app/questions/views.py
> +
@DaisukeMiyazaki 
なるほど！確かに質問が増えることを想定した設計のほうがいいですね…！
こちらで反映するようにします！

2023-07-10 08:57 UTC, kanakof commented on app/questions/forms.py
@DaisukeMiyazaki 
了解しました！使わない部分、消しました！
forms.pyは、大輔が書いてくれた記録用の記載を追加して、残しました！

2023-07-10 09:01 UTC, kanakof commented on app/questions/fixtures/questions.yaml
@DaisukeMiyazaki 
こちら、ラインしました！

2023-07-10 15:45 UTC, kanakof commented
@DaisukeMiyazaki 
もらったレビュー反映しました＆cssファイルやhtmlなどの体裁を最終調整しました。
（staticパスも不具合生じていたので、修正しました）
こちらでマージ許可お願いします！

2023-07-17 01:39 UTC, DaisukeMiyazaki approved these changes
再レビュー不要ですー！

2023-07-17 01:39 UTC, DaisukeMiyazaki commented on app/app/settings.py
> +STATIC_ROOT = os.path.join(BASE_DIR, 'questions/static')
imo: ここは変更前が正解で、htmlのほうで/question なら直指定が良いかと。/answerや他のappが増えることを想定すると。

2023-07-17 02:18 UTC, merged