Feature/rds
kanakof/personality_django pull request #4
Opened 2023-06-10 06:56 UTC by kanakof

RDSの構築をメインにやっています！

2023-06-11 09:06 UTC, kanakof commented
@DaisukeMiyazaki 
一旦、たたきで作ったRDS共有します！
見てくれてありがとう！！！

2023-06-11 10:25 UTC, DaisukeMiyazaki requested changes
@kanakof とりあえずモデルだけレビューしました！コメント確認ください！

2023-06-11 10:25 UTC, DaisukeMiyazaki commented on app/questions/models.py
> +
@kanakof これはアンチパターンです、そもそもフィードにはもっとspecificな命名をしないと answer.item とったときに何だかわかりません

2023-06-11 10:25 UTC, DaisukeMiyazaki commented on app/questions/models.py
> +
answerとquestionの関係は1to1です

2023-06-11 10:25 UTC, DaisukeMiyazaki commented on app/questions/models.py
> +    bloodtype = models.CharField(choices=BLOODTYPE_CHOICES, max_length=2, default=(''))
@kanakof Userの間違い？質問に性別と血液型がつくのはおかしいかと

2023-06-12 04:28 UTC, kanakof commented on app/questions/models.py
> +    bloodtype = models.CharField(choices=BLOODTYPE_CHOICES, max_length=2, default=(''))
@DaisukeMiyazaki 
この質問に紐づけようと思って、性別と血液型の項目を作っていた！
でも、そもそもUserに紐づけるのかな…？

<img width="530" alt="image" src="https://github.com/kanakof/personality_django/assets/130880102/51b41658-c2c5-417d-9cd7-c9e9dd2d98b1">

2023-06-12 04:29 UTC, kanakof commented on app/questions/models.py
> +
@DaisukeMiyazaki 
確認ありがとうございます！
なるほど…！IntegerFieldではなく、より細かい命名ということでしょうか？

2023-07-04 08:57 UTC, kanakof commented
一旦こちらはcloseして、新しくrdsでブランチ作ります！

2023-07-04 08:57 UTC, closed without merging